"""CounterfactualMarkovChain: Gumbel-max counterfactual trajectories.

Two properties pin the construction: with the factual matrix as the
counterfactual one, abduction reproduces the observed trajectory exactly
(every draw); and on binding events generated by conformational selection or
by induced fit, the probability of necessity -- would this molecule have
closed without the ligand? -- separates the mechanisms, as in notebook 09
section 4 (there 0.14 against 0.80).
"""
import numpy as np
import pytest

from IMP.bff import CounterfactualMarkovChain

OPEN, CLOSED = 0, 1


def propagator(oc, co, dt=0.2):
    pi = np.array([co, oc]) / (oc + co)
    return pi[None, :] + (np.eye(2) - pi[None, :]) * np.exp(-(oc + co) * dt)


P_APO = propagator(0.1, 0.1)
P_CS = propagator(0.1, 0.02)      # binds closed, ligand stabilises closed
P_IF = propagator(1.0, 0.02)      # binds open, ligand drives closure


def event(P_bound, bind_from, rng, n_after=10):
    s = rng.integers(2)
    while not (s == bind_from and rng.random() < 0.05):
        s = rng.choice(2, p=P_APO[s])
    traj = [s]
    for _ in range(n_after):
        traj.append(rng.choice(2, p=P_bound[traj[-1]]))
    return traj


def test_the_factual_matrix_reproduces_the_observed_trajectory():
    chain = CounterfactualMarkovChain(P_IF.ravel(), 2)
    traj = [0, 0, 1, 1, 1, 0, 1, 1]
    paths = np.reshape(chain.get_counterfactual_trajectories(traj, P_IF.ravel(), 200, 3), (200, -1))
    assert np.all(paths == np.array(traj)[None, :])


def test_steps_before_the_intervention_follow_the_observation():
    chain = CounterfactualMarkovChain(P_IF.ravel(), 2)
    traj = [0, 0, 1, 1, 1, 1, 1, 1]
    paths = np.reshape(chain.get_counterfactual_trajectories(traj, P_APO.ravel(), 100, 4, from_step=3),
                       (100, -1))
    assert np.all(paths[:, :4] == np.array(traj[:4])[None, :])
    occupancy = np.reshape(chain.get_counterfactual_occupancy(traj, P_APO.ravel(), 100, 4, 3), (len(traj), 2))
    assert np.allclose(occupancy.sum(1), 1.0)


def test_probability_of_necessity_separates_selection_from_induced_fit():
    rng = np.random.default_rng(5)
    pn = {}
    for name, (P, bind_from) in {"CS": (P_CS, CLOSED), "IF": (P_IF, OPEN)}.items():
        chain = CounterfactualMarkovChain(P.ravel(), 2)
        values = []
        for k in range(60):
            traj = event(P, bind_from, rng)
            if traj[-1] == CLOSED:
                values.append(chain.get_counterfactual_probability(traj, P_APO.ravel(), OPEN, 300, k))
        pn[name] = np.mean(values)
    assert pn["CS"] < 0.3
    assert pn["IF"] > 0.6


def test_impossible_steps_and_bad_matrices_are_refused():
    P = np.array([[1.0, 0.0], [0.5, 0.5]])
    chain = CounterfactualMarkovChain(P.ravel(), 2)
    with pytest.raises(ValueError):
        chain.get_counterfactual_trajectories([0, 1], P_APO.ravel(), 10, 1)   # 0 -> 1 has P = 0
    with pytest.raises(ValueError):
        CounterfactualMarkovChain([0.5, 0.4, 0.5, 0.5], 2)                    # row does not sum to 1
    with pytest.raises(ValueError):
        chain.get_counterfactual_trajectories([0, 0], [1.0, 0.0, 0.5], 10, 1)
